### ISSUE TITLE
Takes up to 20 seconds to open connection

### ISSUE THREAD

**Issue by chadgrant** [couchbase/docker#103]
using gocb, running couchbase in docker. 

Opening a connection takes up to 20 seconds.

Problem for our whole team

**Comment by ceejatec** [comment]
Need a little bit more information here. What version of Couchbase? What platform are you running gocb on? Can you provide a sample of the Go code and database configuration? Have you possibly tried running Couchbase outside Docker to confirm that the problem is unique to the Docker container?

**Comment by chadgrant** [comment]
```
FROM couchbase/server:enterprise-5.1.0

COPY data /opt/couchbase/data
COPY configure.sh /configure.sh

RUN chmod 777 /entrypoint.sh && \
    chmod 777 /configure.sh 

CMD [ "/configure.sh" ]
```

configure.sh:

```
set -m
#set -e

/entrypoint.sh couchbase-server &

until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:8091); do
    echo 'waiting on rest api ...'
    sleep 3
done

#configure cluster
couchbase-cli cluster-init --cluster-username=$CB_USERNAME --cluster-password=$CB_PASSWORD \
    --cluster-port=8091 --cluster-ramsize=300 --cluster-index-ramsize=300 \
    --services=data,index,query

#create bucket
couchbase-cli bucket-create -c 127.0.0.1 --bucket-type=couchbase --bucket-ramsize=200 \
    --bucket=$CB_BUCKET -u $CB_USERNAME -p $CB_PASSWORD

for attempt in $(seq 5)
do
    curl -s http://127.0.0.1:8093/admin/ping > /dev/null \
    && break

    echo "Waiting for query service..."
    sleep 3
done

#create indexes
cbq -e http://127.0.0.1:8093 -u $CB_USERNAME -p $CB_PASSWORD -q=true -f="/opt/couchbase/data/indexes.txt"

#import data
cbimport json -v -u $CB_USERNAME -p $CB_PASSWORD -c 127.0.0.1:8091 -b $CB_BUCKET -f list -g key::%_id% -d file://opt/couchbase/data/data.json

fg 1
```

as far as code goes, using gocb with standard Open cluster, Authenticate, Open Bucket

**Comment by chadgrant** [comment]
I figured it out, if you use couchbase:// instead of http://, it enumerates DNS srv records (which in our case do not exist) and that is what is taking 20+ seconds.

Also, the gocb project has issue reporting turned off, I have found bugs, sql injection etc... Would be nice to be able to report them.

**Comment by tleyden** [comment]
@chadgrant thanks for posting the follow-up (good to know about that).  

There's two other ways you can report gocb issues:

- [Couchbase Forum](https://forums.couchbase.com/t/limit-total-storage-per-user/16969)
- [Couchbase Jira tracker](https://issues.couchbase.com/secure/Dashboard.jspa)  

I realize it's a bit higher friction than github, but I would recommend biting the bullet since the gocb folks closely monitor both of those closely.

**Comment by ceejatec** [comment]
@chadgrant  Indeed, thanks for following up, and I'm glad you've found a workaround. With the initial report, I suspected DNS would play a role (if you see random 30-second pauses, it's almost *always* DNS), but I don't know if I would have been able to figure out how or what was happening in this case.
