### ISSUE TITLE
Couchbase for ARMv8

### ISSUE THREAD

**Issue by khasim** [couchbase/docker#107]
Hello,

Are there any plans to officially host / support all the required dependent binaries for ARMv8 ? Any thing I can help with to make it possible ?

Regards,
Khasim

**Comment by tleyden** [comment]
There are few open issues for that:

* Couchbase Server -- https://issues.couchbase.com/browse/MB-17363
* Sync Gateway -- https://issues.couchbase.com/browse/MB-25541

Closing this as a duplicate.

**Comment by tleyden** [comment]
@ceejatec thanks, I didn't realize they were private.

**Comment by khasim** [comment]
If you don't mind, will it be possible to share more details on this issue for supporting ARM ?
Can we offer to work on fixing any known bugs / issues to get couchbase working for ARM ? Not sure how complicated or easy it is.

Regards,
Khasim

**Comment by ceejatec** [comment]
We estimated a minimum of a month to get a build of Server, including time to port the many third-party libraries and tools which are required to do the build. There are also significant ongoing costs for testing and upgrading the dependencies for future releases. So far there's no evidence there'd be a return on that investment.

**Comment by ceejatec** [comment]
I still think it's vanishingly unlikely. There have been no requests from paying or potential customers, and as I said, it's a tremendous amount of work.

**Comment by mmarmm** [comment]
No problem, thought I would ask. I'll try and get you some customers then.
