### ISSUE TITLE
Can't cluster-init with ram setting on rc0

### ISSUE THREAD

**Issue by corbinu** [couchbase/docker#12]
In rc0 when I run cluster-init command I get an error as it always defaults to the largest possible index ignoring the --cluster-index-ramsize property. 

This works fine in enterprise-4.0.0-3508

**Comment by tleyden** [comment]
@corbinu can you paste the error?  Also anything else you can provide like the actual rest api http requests would be really useful.

**Comment by corbinu** [comment]
Here is the run I have no idea what the http request the cli makes looks like

```
corbinu:~/ $ docker run -d -p 8091:8091 couchbase/server:enterprise-4.0.0-rc0
5f978d27397489968c3bb56c082d7881262fa478d1ea29b23e9d5d729838e877
corbinu:~/ $ docker exec -it 5f978d27397489968c3bb56c082d7881262fa478d1ea29b23e9d5d729838e877 /bin/bash

root@5f978d273974:/# couchbase-cli cluster-init -c 127.0.0.1:8091 \
>        --cluster-username=Administrator \
>        --cluster-password=password \
>        --cluster-port=8080 \
>        --services=data,index \
>        --cluster-ramsize=300 \
>        --cluster-index-ramsize=200
ERROR: unable to setup services (400) Bad Request
["insufficient memory to satisfy memory quota for the services (requested quota is 1451MB, maximum allowed quota for the node is 796MB)"]
```

**Comment by tleyden** [comment]
Thanks!  I've filed a [Jira ticket](https://issues.couchbase.com/browse/MB-16233) for the Couchbase Server tools team.  Please watch that ticket.

**Comment by tleyden** [comment]
@corbinu There are some updates on https://issues.couchbase.com/browse/MB-16233
