### ISSUE TITLE
sync-gateway doesn't work with wait-for-it.sh

### ISSUE THREAD

**Issue by rominf** [couchbase/docker#120]
I'm having problems with running `sync-gateway` from `wait-for-it.sh`. Without `wait-for-it.sh` `sync-gateway` starts, with it - doesn't start.
The full description is on [CouchBase forums](https://forums.couchbase.com/t/sync-gateway-in-docker-doesnt-start-from-wait-for-it-sh/19739).

**Comment by rominf** [comment]
This issue on `wait-for-it.sh` issue tracker: https://github.com/vishnubob/wait-for-it/issues/63

**Comment by bbrks** [comment]
Hi @rominf, I've left a reply on the original forum post with some advice. `wait-for-it.sh` doesn't seem like an appropriate choice to block startup of SG.

**Comment by rominf** [comment]
@bbrks, thank you.
