### ISSUE TITLE
Duplicate quotations in entrypoint script

### ISSUE THREAD

**Issue by timm088** [couchbase/docker#123]
https://github.com/couchbase/docker/commit/ce6c779644752958f55cf2635ca36251fdfd4c63

That commit includes an erroneous use of quotations, that causes the script to break.

The commit itself has been on master for ~2 months ... taking a guess here, but the recent credentials breach on dockerhub seems to have forced a rebuild of your images, and now they a broken?

`"$(whoami)""` should be `"$(whoami)"`

**Comment by ceejatec** [comment]
Thank you very much for the report! FYI, it wasn't actually the security breach that caused the image rebuilds - Docker Hub changed their autobuild mechanism recently and unintentionally opted us in to automatic rebuilds whenever we push a change to this repository in GitHub, which I happened to do on Friday. I've fixed that autobuild now, which I guess means I'll have to manually rebuild everything when I push the fix to this whoami bug.

**Comment by mtrossbach** [comment]
When will the new image be built?

**Comment by ceejatec** [comment]
I'm working on it now. The new autobuild mechanism doesn't work at all with the way we've generated our Dockerfiles so I'm having to hack something together quickly for the time being.

**Comment by ceejatec** [comment]
Rebuilds are queued up. It'll take a while for Docker Hub to chew through them, but the most recent Enterprise Edition tags :6.0.1 (aka :enterprise and :latest) and :5.5.4 have been fixed already, as well as the most recent Community Edition tag :community-6.0.0 (aka :community).

**Comment by timm088** [comment]
Did the rebuilds complete for all tags @ceejatec

**Comment by ceejatec** [comment]
Yes. I had to re-kick a few today that didn't trigger for whatever reason, but at this point all supported images should be refreshed.
