### ISSUE TITLE
Curl does not work in Ubuntu 12.04 container 

### ISSUE THREAD

**Issue by corbinu** [couchbase/docker#13]
I am trying to get around https://github.com/couchbase/docker/issues/12

By using the REST API rather then couchbase-cli

How ever when ever I use curl in the container I get "curl: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory"

It seems their are two solutions one install updated curl from "ppa:costamagnagianfranco/ettercap-stable-backports"

Or rebase the container on either Debian 7 or Ubuntu 14.04

I would be happy to issue a PR for either option.

**Comment by hookenz** [comment]
Containers are meant to be minimal.  I'd just install them directly for now until a fix is produced for docker-cli

**Comment by corbinu** [comment]
@hookenz I am sorry but I have no idea what your talking about curl is installed in the default Ubuntu containers from docker so clearly it is meant to be available. Plus this is inside the container it has absolutely nothing to do with the docker-cli?

**Comment by hookenz** [comment]
@corbinu - fork it and create an updated curl if you really need that.  But in the long term, best to keep things as standard as possible and not pull in backported libs into the base.

**Comment by corbinu** [comment]
Well I will take thats a vote for upgrading the base to Debian 7 or Ubuntu 14.04 then. The simple fact is it needs to be possible to create a cluster via terminal. Since couchbase-cli is not going to be fixed until Couchbase 4.1 that leaves making sure that curl works in the image. How is unimportant

**Comment by ceejatec** [comment]
Check your PATH. If you're picking up curl from /opt/couchbase/bin, you'll need to add /opt/couchbase/library to LD_LIBRARY_PATH.

**Comment by hookenz** [comment]
Or use the web ui.  That's what I do.

If you're running the cluster remotely and have ssh access, you can use ssh with the -L option to access the web ui.  e.g.

ssh -L 8091:localhost:8091 hostname

Then point your browser to http://localhost:8091 and setup the cluster from there.
You can also get socks access with -D on ssh and use tsocks to transparently add socks support to any app that needs to access your cluster.  I have a few that need that to put the views into the couchbase cluster.

**Comment by corbinu** [comment]
@ceejatec I am sorry but that does not appear to fix the issue

```
 docker run -it -p 8091 couchbase/server:enterprise-4.0.0-rc0 /bin/bash                                                                                           [20:27:51]
root@7fa31cff63c3:/# export  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/couchbase/library
root@7fa31cff63c3:/# curl
curl: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

**Comment by hookenz** [comment]
@ceejatec - use the web ui, see my previous comment.

**Comment by ceejatec** [comment]
I'm sorry, my phone auto-corrected the path. You need /opt/couchbase/lib on LD_LIBRARY_PATH.

**Comment by corbinu** [comment]
@ceejatec No worries happens to everybody! That works great and I have created a PR to fix the issue thanks! Let me know if there is any changes you want made to it before merging.

**Comment by tleyden** [comment]
@ceejatec I merged this PR since it looked additive and harmless, ping me if you see any potential issues.

**Comment by tleyden** [comment]
Also, I triggered a [dockerhub build](https://hub.docker.com/r/couchbase/server/) and set it to auto-build on new commits of this repo.
