### ISSUE TITLE
couchbase operator issue

### ISSUE THREAD

**Issue by vishnugsinghal** [couchbase/docker#130]
I have created couchbase operator and cluster with following server configuration.

servers:
    # Name for the server configuration. It must be unique.
    data_services:
      size: 2
      services:
        - data
      serverGroups: []
      # Pod defines the policy to create pod for the couchbase pod.
      # pod: {}
      pod:
        nodeSelector:
          nodeLabel: appsec-snp-couchbase
    index_services:
      # Size of the couchbase cluster.
      size: 2
      # The services to run on nodes
      services:
        - index
        - query
        - search
        - eventing
        - analytics
      # ServerGroups define the set of availability zones we want to distribute pods over.
      serverGroups: []
      # Pod defines the policy to create pod for the couchbase pod.
      # pod: {}

Following issue i see in the couchbase operator logs and one of node is pending in dashboard.

time="2019-06-24T19:32:16Z" level=info msg="┌──────────────────────────────────────────┬──────────────────┬────────────────┬────────────────┐" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="│ Server                                   │ Version          │ Class          │ Status         │" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="├──────────────────────────────────────────┼──────────────────┼────────────────┼────────────────┤" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="│ couchbase-cluster-couchbase-cluster-0000 │ enterprise-6.0.1 │ **all_services**   │ managed+warmup │" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="│ couchbase-cluster-couchbase-cluster-0001 │ enterprise-6.0.1 │ **all_services**   │ managed+active │" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="│ couchbase-cluster-couchbase-cluster-0002 │ enterprise-6.0.1 │ **all_services**   │ managed+active │" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="│ couchbase-cluster-couchbase-cluster-0003 │ enterprise-6.0.1 │ data_services  │ managed+active │" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="│ couchbase-cluster-couchbase-cluster-0004 │ enterprise-6.0.1 │ data_services  │ managed+active │" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="│ couchbase-cluster-couchbase-cluster-0005 │ enterprise-6.0.1 │ index_services │ managed+active │" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="│ couchbase-cluster-couchbase-cluster-0006 │ enterprise-6.0.1 │ index_services │ managed+active │" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="└──────────────────────────────────────────┴──────────────────┴────────────────┴────────────────┘" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="Skipping reconcile loop because some nodes are warming up" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-06-24T19:32:16Z" level=info msg="reconcile finished" cluster-name=couchbase-cluster-couchbase-cluster module=cluster

Two issues : 
1) Basically I havent not created all_services in the server, but then i three pods being created with that configuration Why so ?

2) Why this one of the node goes in pending issue ?

Couchbase image is enterprise 6.0.1

Regards
Vishnu

**Comment by vishnugsinghal** [comment]
Also i see  on dashboard 

Code: 5000, Message: " Indexer In Warmup State. Please retry the request later. from [couchbase-cluster-couchbase-cluster-0006.couchbase-cluster-couchbase-cluster.default.svc:9101] - cause: Indexer In Warmup State. Please retry the request later. from [couchbase-cluster-couchbase-cluster-0006.couchbase-cluster-couchbase-cluster.default.svc:9101]"

**Comment by ceejatec** [comment]
This repository is for the Dockerfiles that create Couchbase Server and Sync Gateway docker images. The Couchbase Autonomous Operator is an unrelated product. I will point one of the Operator devs to this report, but my best suggestion for support would be the Couchbase Forums.

**Comment by ingenthr** [comment]
Agreed with @ceejatec - best to post to https://forums.couchbase.com/c/couchbase-server/Kubernetes with a well formatted set of config and log output.  We can help more from there.
