### ISSUE TITLE
couchbase-operator /couchbase-cluster rebalancing issue

### ISSUE THREAD

**Issue by vishnugsinghal** [couchbase/docker#131]
Rebalance exited with reason {service_rebalance_failed,index,
{linked_process_died,<21690.7456.0>,
{no_connection,"index-service_api"}}}

**Comment by ceejatec** [comment]
Again, @vishnugsinghal , this repository is for the Dockerfiles, not for Server or Operator. This is not the right place to file bug reports or support requests. Please post details on the Couchbase Forums.
