### ISSUE TITLE
couchbase operator one cluster couchbase pod in completed state

### ISSUE THREAD

**Issue by vishnugsinghal** [couchbase/docker#132]
Hi,

couchbase-cluster-couchbase-cluster-0000                 1/1     Running       0          5d6h
couchbase-cluster-couchbase-cluster-0001                 0/1     Completed     0          5d6h

I see one of the couchbase cluster pod is in completed state and operator logs says  following

time="2019-07-08T13:50:07Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:50:15Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:50:23Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:50:31Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:50:39Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:50:47Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:50:56Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:51:04Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:51:12Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:51:20Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:51:28Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:51:36Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster
time="2019-07-08T13:51:44Z" level=error msg="failed to update members: cluster contains node `couchbase-cluster-couchbase-cluster-0001` which cannot be managed. Failover/Rebalance is recommended" cluster-name=couchbase-cluster-couchbase-cluster module=cluster

Regards
Vishnu G Singhal

**Comment by bbrks** [comment]
Hi @vishnugsinghal - like @ceejatec alluded to in the other two issues you filed (#130 & #131), this repo is not for the Couchbase Server Operator.

Please post details on the [Couchbase Forums](https://forums.couchbase.com/) to get help.
