### ISSUE TITLE
CPU usage in Docker Desktop for Mac

### ISSUE THREAD

**Issue by hubgit** [couchbase/docker#144]
Following the documentation in https://hub.docker.com/_/couchbase it's easy to get to a state where `com.docker.hyperkit` is running at >50% CPU even when Couchbase is idle:

1. Run `docker run -d --name db -p 8091-8094:8091-8094 -p 11210:11210 couchbase` to start the Couchbase container.
2. Open http://localhost:8091 and set up a new cluster with the default settings.
3. Load the `beer-sample` data into a new bucket.

The stats will show the server running between 10% and 20% CPU, and `com.docker.hyperkit` will now be consistently running between 50% and 60% CPU.

This is using the latest version of Docker Desktop in macOS 10.15.6.

**Comment by ceejatec** [comment]
This appears to be a recurring issue with Docker on MacOS; most recent Docker ticket is https://github.com/docker/for-mac/issues/3499 , which is still open and active as recently as today. I can't see any way this would be Couchbase-server specific, and at any rate Docker-on-Mac isn't a supported configuration for Server (although it should be fine for general tests and experimentation). Closing this ticket.
