### ISSUE TITLE
Syncgateway exposing its version on landing page(root url)

### ISSUE THREAD

**Issue by alliedgorn** [couchbase/docker#145]
This could violate security constraints in some enterprises as attackers could utilise this information.

It would be great if user could set some kind of authorization to this page or has a way to hide this information.

**Comment by bbrks** [comment]
Hi @alliedgorn 

This is being tracked as part of a broader task in Sync Gateway, which also covers omitting version numbers from Server headers:
https://issues.couchbase.com/browse/CM-530 

We need to ensure clients aren't reliant on this version for compatibility reasons before we start removing it.

I'm closing this issue, as it doesn't pertain to the general Couchbase Docker project, but feel free to follow along on the above Jira ticket.

Thanks,
Ben
