### ISSUE TITLE
Does not run out of the box on centos6.7

### ISSUE THREAD

**Issue by tleyden** [couchbase/docker#15]
Due to https://github.com/docker-library/official-images/issues/339#issuecomment-142060521, the `initscripts` package must be defined first.  Maybe this package should be installed in the Dockerfile.

**Comment by ceejatec** [comment]
Our official image is based on Ubuntu now - is this still relevant?

**Comment by tleyden** [comment]
Sorry, I got confused.  I ran into this when manually installing couchbase on a vanilla centos docker container.
