### ISSUE TITLE
Expose port 8093

### ISSUE THREAD

**Issue by arun-gupta** [couchbase/docker#17]
Port 8093 need to be exposed in order for queries to be executed. Otherwise it throws the following exception:

```
17:54:32,917 WARN  [com.couchbase.client.core.endpoint.Endpoint] (cb-io-1-4) [null][QueryEndpoint]: Could not connect to endpoint, retrying with delay 32 MILLISECONDS: : java.net.ConnectException: Connection refused: dockerhost/192.168.99.100:8093
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at com.couchbase.client.deps.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
```

**Comment by hookenz** [comment]
EXPOSE is only useful for linked containers or if you use -P.  In the mean time you can call docker run with -p 8093:8093.  I usually run it with -net=host actually.

**Comment by arun-gupta** [comment]
That worked for me but I think documenting it would be useful.

**Comment by ceejatec** [comment]
It's documented in code inasmuch as the Dockerfile now specifies it. I'm not sure what user documentation it would be relevant to put this information in - this isn't something that a user can or should control.

**Comment by ceejatec** [comment]
I've pushed 01494d1e07117fdaca58221f5e78e82ec03ba446 which adds 8093 to the EXPOSE list. As @hookenz points out, this isn't actually very valuable, but it's useful to document ports that might be interesting.

We should probably add some documentation to the README describing the ports that are of interest and why. Arun, do you think you might be able to take a crack at that? I can propose the change to the official image documentation once we've updated it here in this repository.

**Comment by ceejatec** [comment]
Forgot to close this.
