### ISSUE TITLE
Cannot run community server

### ISSUE THREAD

**Issue by alastaircoote** [couchbase/docker#20]
I'm a Docker and Couchbase newbie, so I'll preface this by saying I might be doing something totally wrong, but according to the guide, I ran:

    docker run -d -v ~/couchbase:/opt/couchbase/var -p 8091:8091 couchbase/server

Then tried to load `localhost:8091`, and... connection refused. The log shows:

    Starting Couchbase Server -- Web UI available at http://<ip>:8091

I'm on OS X, running Docker 1.8.3.

**Comment by alastaircoote** [comment]
I'm an idiot. OS X, of course, spins up a Docker container VM. So I wanted to go to a different IP:8091. Ignore me, sorry!

**Comment by ceejatec** [comment]
Glad you worked it out. I do notice that our documentation specifically mentions "localhost:8091", which isn't accurate when running on MacOS or Windows. We should correct that. Sorry for the confusion.
