### ISSUE TITLE
Couchbase service stopped and Docker container didn't restart

### ISSUE THREAD

**Issue by stakach** [couchbase/docker#22]
This was on Redhat 7 (SELinux) with docker 1.7.1
At this point we are not sure why the service stopped, we'll update this issue if we can work out what happened. Manually starting the service using `service couchbase-server start` wasn't able to start the server again, so we restarted the docker container and everything is working properly.

Obviously this should happen and we're surprised the container didn't restart. I can't guarantee it'll happen again, however if it does what information would be helpful to gather?

**Comment by ceejatec** [comment]
I'm not sure whether you ran "service couchbase-server start" inside or outside the container, but in either case, it shouldn't work - the container isn't running init(8), and the normal init.d scripts aren't used.

If the server had completely crashed, I am surprised as you are that it didn't restart. We use "runit" in the container to monitor and restart the server, and the server itself has a babysitter process to restart child processes.

If it happens again, it would be useful to get a full process listing from inside the container, eg. "docker exec <containerID> ps -ef" to see which portions of the server are up and down. Also, you could collect a full suite of logs for debugging:

docker exec <containerID> cbcollect_info /tmp/logs.zip
docker cp <containerID>:/tmp/logs.zip logs.zip

**Comment by stakach** [comment]
Thanks for the advice! I'll reopen if it happens again with more details
