### ISSUE TITLE
Container should include all system utilities expected for cbcollect_info

### ISSUE THREAD

**Issue by Chippiewill** [couchbase/docker#24]
- arp
 - cat
 - cbbrowse_logs
 - cbstats
 - curl
 - df
 - dmesg
 - echo
 - filefrag
 - find
 - free
 - getent
 - ifconfig
 - intrstat
 - iostat
 - ip
 - ls
 - lsb_release
 - lshw
 - lsmod
 - lsof
 - lvdisplay
 - mpstat
 - netstat
 - numactl
 - pgrep
 - ps
 - pvdisplay
 - rpm
 - sar
 - sh
 - ss
 - su
 - swapon
 - sysctl
 - tar
 - top
 - ulimit
 - uname
 - uptime
 - vgdisplay
 - vmstat
 - xargs

Many of these utilities (Such as netstat) are not included in the base image. Obviously a few are bundled with Couchbase (Like curl) and some may not be appropriate (Such as rpm), but the majority should be these.

List source: https://raw.githubusercontent.com/membase/ns_server/a643e281c3a2b39aa5791922a1342df2135e2d9a/doc/cbcollect_info_deps.txt

**Comment by hookenz** [comment]
Of those listed, the following do not exist:

- arp
- ifconfig
- iostat
- lsb_release
- lshw
- lsof
- lvdisplay
- mpstat
- netstat
- numacl
- pgrep
- pvdisplay
- rpm
- sar
- vgdisplay

So it it would be best to look at the source code for cbcollect_info and find out how it behaves if something is missing.  Some could probably just be linked to /bin/true.  

lsb_release normally gives details about the distribution.  But I think I'd replace that with a compatible shell script that showed it is running in a container.

**Comment by ceejatec** [comment]
I think this ticket should be recast as "test cbcollect_info in the Docker container and see if there are any problems with the reports it generates".

**Comment by Chippiewill** [comment]
````
==============================================================================
raw /etc/sysconfig/clock
cat /etc/sysconfig/clock
==============================================================================
cat: /etc/sysconfig/clock: No such file or directory
````

````
==============================================================================
System Hardware
lshw -json || lshw
==============================================================================
/bin/sh: 1: lshw: not found
/bin/sh: 1: lshw: not found
````

````
==============================================================================
Extended iostat
iostat -x -p ALL 1 10 || iostat -x 1 10
==============================================================================
/bin/sh: 1: iostat: not found
/bin/sh: 1: iostat: not found
````

````
==============================================================================
relevant lsof output
echo moxi memcached beam.smp couch_compact godu sigar_port cbq-engine indexer projector goxdcr | xargs -n1 pgrep | xargs -n1 -r -- lsof -n -p
==============================================================================
xargs: lsof: No such file or directory
````

````
==============================================================================
LVM info
lvdisplay
==============================================================================
/bin/sh: 1: lvdisplay: not found
==============================================================================
LVM info
vgdisplay
==============================================================================
/bin/sh: 1: vgdisplay: not found
==============================================================================
LVM info
pvdisplay
==============================================================================
/bin/sh: 1: pvdisplay: not found
````

````
Network configuration
ifconfig -a
==============================================================================
/bin/sh: 1: ifconfig: not found
/bin/sh: 1: ifconfig: not found
````

````
==============================================================================
Network status
netstat -anp || netstat -an
==============================================================================
/bin/sh: 1: netstat: not found
/bin/sh: 1: netstat: not found
==============================================================================
Network routing table
netstat -rn
==============================================================================
/bin/sh: 1: netstat: not found
````

````
==============================================================================
Arp cache
arp -na
==============================================================================
/bin/sh: 1: arp: not found
````

````
==============================================================================
Iptables dump
iptables-save
==============================================================================
/bin/sh: 1: iptables-save: not found
````

````
==============================================================================
System activity reporter
sar 1 10
==============================================================================
/bin/sh: 1: sar: not found
````

````
==============================================================================
Interrupt status
intrstat 1 10
==============================================================================
/bin/sh: 1: intrstat: not found
````

````
==============================================================================
Processor status
mpstat 1 10
==============================================================================
/bin/sh: 1: mpstat: not found
````

````
==============================================================================
NUMA data
numactl --hardware
==============================================================================
/bin/sh: 1: numactl: not found
==============================================================================
NUMA data
numactl --show
==============================================================================
/bin/sh: 1: numactl: not found
````

````
==============================================================================
Network statistics
netstat -s
==============================================================================
/bin/sh: 1: netstat: not found
````

`lsb_release` is not required as we get that (for Ubuntu) from `cat /etc/issue`

**Comment by Chippiewill** [comment]
These are all the 'not found' entries in a 4.x cbcollect which I think are relevant. Most of them probably need outright adding, but a couple could probably just be replaced with a shim stating that its not applicable (Such as I think LVM).

**Comment by tleyden** [comment]
I think that the deeper problem is that couchbase isn't packaged as well as it could be -- eg, `yum/apt-get install couchbase-server` should pull all required dependencies.

**Comment by arun-gupta** [comment]
+1 to @tleyden comment. This will also bring another opportunity to install Couchbase server easily on Ubuntu-based systems.

**Comment by ceejatec** [comment]
Maaaaybe. I'm not sure we want to expand our packages to list everything that cbcollect_info *might* use as a hard requirement.

**Comment by ceejatec** [comment]
Finally looking into this and updating the images. I started a container using the latest 4.1.1 Enterprise image, and ran cbcollect_info. Here are all the things that returned "Exit code xxx" rather than "OK" and what I did/didn't do about them.

- FYI, ifconfig, arp, and netstat actually are installed in the latest images - I'm guessing they're in the Ubuntu 14.04 base that we use for 4.x, but not in Ubuntu 12.04 base that we use for 3.x

- Following commands now work (or at least don't exit with a non-zero code) due to installing the requisite software in the image:

```
System Hardware (lshw -json || lshw) - Exit code 127
Extended iostat (iostat -x -p ALL 1 10 || iostat -x 1 10) - Exit code 127
relevant lsof output (echo moxi memcached beam.smp couch_compact godu sigar_port cbq-engine indexer projector goxdcr | xargs -n1 pgrep | xargs -n1 -r -- lsof -n -p) - Exit code 127
System activity reporter (sar 1 10) - Exit code 127
Processor status (mpstat 1 10) - Exit code 127
NUMA data (numactl --hardware) - Exit code 127
NUMA data (numactl --show) - Exit code 127
```

- Following commands do not make sense to run inside a container, so I created a stub command that reports "Running inside Docker container - step skipped":

```
LVM info (lvdisplay) - Exit code 127
LVM info (vgdisplay) - Exit code 127
LVM info (pvdisplay) - Exit code 127
Iptables dump (iptables-save) - Exit code 1
```

- Following commands/actions will only work on Red Hat-like systems and are clearly expected to fail anyway on Debian-like systems, so I took no action:

```
raw /etc/sysconfig/clock (cat /etc/sysconfig/clock) - Exit code 1
Distro version (cat /etc/redhat-release) - Exit code 1
Distro version (cat /etc/SuSE-release) - Exit code 1
Installed software (rpm -qa) - Exit code 127
Transparent Huge Pages data (cat /sys/kernel/mm/redhat_transparent_hugepage/enabled) - Exit code 1
Transparent Huge Pages data (cat /sys/kernel/mm/redhat_transparent_hugepage/defrag) - Exit code 1
```

- Similarly, the follow appears to be unique to Solaris and so shouldn't be expected to succeed on Ubuntu, so no action by me:

```
Interrupt status (intrstat 1 10) - Exit code 127
```

- The following is taking a shotgun approach to gathering system logs, many of which don't exist inside a container. It is quite likely that at least SOME of these will not exist on any given system, and so the command is expected to possibly raise an error and that's OK; no action by me:

```
All logs (tar cz /var/log/syslog* /var/log/dmesg /var/log/messages* /var/log/daemon* /var/log/debug* /var/log/kern.log* 2>/dev/null) - Exit code 2
```

- And the following really shouldn't work anywhere anymore and is presumably included for historical interest only, so no action by me:

```
System log (cat /var/adm/messages) - Exit code 1
```

**Comment by ceejatec** [comment]
FYI: I lied a bit about numactl working - it still doesn't, but it's a different issue not related to Docker. I will file a separate Couchbase ticket regarding that.

**Comment by ceejatec** [comment]
Also FYI, the Docker image for 4.1.1 increased in size by less than 8MB to add the necessary tools.
