### ISSUE TITLE
Enable stdio logging

### ISSUE THREAD

**Issue by tleyden** [couchbase/docker#3]
As mentioned in https://github.com/couchbase/docker/pull/2#issuecomment-102445531, the logging situation could be improved a bit.

From [MB-15028](https://issues.couchbase.com/browse/MB-15028), the suggest command is:

```
/opt/couchbase/bin/couchbase-server -- -noinput -ns_server dont_suppress_stderr_logger true
```

**Comment by ceejatec** [comment]
FYI, I've tried this locally. I'm not sure we want this out-of-the-box... merely starting the server and going through the initial setup wizard resulted in over 15,000 lines of log information. Is that valuable?

I don't know if there's a way to reduce the verbosity here, I'm asking ns_server team.

**Comment by tleyden** [comment]
It doesn't seem like this is going to change anytime soon, so I'm just going to close this to reduce ticket pollution

**Comment by themanifold** [comment]
I just wanted to say for anyone banging their heads against a wall that that you can make the logging [less verbose](https://forums.couchbase.com/t/beam-smp-use-too-much-cpu-couchbase-server-version-5-0-1/15796/2):
```
/opt/couchbase/bin/couchbase-server -- -noinput -ns_server dont_suppress_stderr_logger true -ns_server loglevel_stderr info
```
You can change `info` to any of the values mentioned here: https://github.com/couchbase/ns_server/blob/master/doc/logging-guidelines.txt

**Comment by tleyden** [comment]
Thanks for sharing that out
