### ISSUE TITLE
3.1.3 Enterprise Tag missing

### ISSUE THREAD

**Issue by dmaier-couchbase** [couchbase/docker#32]
Hello,

the latest 3.x release is currently 3.1.3. I would like to do some testing with it by using Docker in order to spin up my Couchbase cluster. However, I just realized that 3.1.3 is not yet available as a tag ( https://hub.docker.com/r/couchbase/server/tags/ ). 

Could you please add the 3.1.3 tag?

Regards,
David

**Comment by tleyden** [comment]
Build in progress on dockerhub:

https://hub.docker.com/r/couchbase/server/builds/bypiokhxzm7bj97ktrreygv/

**Comment by tleyden** [comment]
Looks like it worked
