### ISSUE TITLE
Unexpected error in Couchbase Server logs

### ISSUE THREAD

**Issue by tleyden** [couchbase/docker#46]
Steps to repro:

* Spin up AWS AMI with centos7
* Install latest docker version as of today
* Run `docker run --net=couchbase -d --name couchbase-server -p 8091-8094:8091-8094 -p 11210:11210 couchbase`
* View docker logs 

```
[centos@ip-172-31-11-161 ~]$ docker logs ba16
Starting Couchbase Server -- Web UI available at http://<ip>:8091
{error_logger,{{2016,8,5},{5,12,30}},"global_trace:~n~p",[{loop_the_locker,{multi,[],[],[],'nonode@nohost',false,false}}]}
```

What is the `{error_logger,{{2016,8,5},{5,12,30}},"global_trace:~n~p",[{loop_the_locker,{multi,[],[],[],'nonode@nohost',false,false}}]}` message about?

**Comment by ceejatec** [comment]
I haven't a clue. Erlang error messages are beyond arcane. I'd suggest running it by someone in ns_server, Aliaksey perhaps, to understand what it means.

**Comment by tleyden** [comment]
Filed https://issues.couchbase.com/browse/MB-20430
