### ISSUE TITLE
4.0.0-4051 Community Edition (build-4051) View Bad Match Error

### ISSUE THREAD

**Issue by dazthorpe** [couchbase/docker#47]
Hi

I'm using the 4.0.0-4051 Community Edition (build-4051) image and I'm using the -v option when starting to map /var to a local folder on the host machine.  Basically all of my views fail with the following:

```
from:
http://172.17.0.2:8092/Fixtures/_design/dev_whoscored/_view/test?stale=false&inclusive_end=true&connection_timeout=60000&limit=10&skip=0
reason:
{badmatch,{error,etxtbsy}} ([{couch_set_view_group,handle_info,2, [{file,"/home/couchbase/jenkins/workspace/sherlock-unix/couchdb/src/couch_set_view/src/couch_set_view_group.erl"}, {line,1168}]}, {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]}, {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}])
```

I can view documents via the Documents button, but the views consistently fail.

Thanks in advance

Darren

**Comment by ceejatec** [comment]
/var has no particular meaning to Couchbase Server in a container. Couchbase writes all data, logs, etc to /opt/couchbase/var, which is the directory you need to mount if you want persistence.

Also be aware that Couchbase Server runs as UID 1000 inside the container, so whatever host directory you mount needs to be writable by that user.

If you still have trouble, try running the container with no -v options at all as a test. If that still causes view problems, then there's something else entirely that's wrong.

**Comment by dazthorpe** [comment]
Hi 

Thanks for the feedback.  I should have been more specific, here's the command I use to launch the container:

docker run -v '//c/Users/USERNAME/couchbase/var:/opt/couchbase/var' -p 8091-8093:8091-8093 -p 11210:11210 --add-host="localhost:10.0.2.2" couchbase/server:latest

I think this has something to do with the files being locked by virtual box.  When I drop the -v option couchbase behaves as expected.  According to Process Explorer it is only virtual box locking the shared folders, so it's old that a process running within virtual box would have a problem.

I'll check the UID permissions as per your suggestion.

Thanks

Darren

**Comment by ceejatec** [comment]
Closing this is as it is quite old. It appears #140 may be the same issue, so you could follow any developments there, but as it is evidently unique to Docker on Windows it is not a high priority.

**Comment by ceejatec** [comment]
After some internal investigation, I've opened a product bug about this: https://issues.couchbase.com/browse/MB-37452
