### ISSUE TITLE
Official image isn't runable on Openshift

### ISSUE THREAD

**Issue by voanhduy1512** [couchbase/docker#68]
Hi,

I try to deploy couchbase on Openshift but it looks like the image run as `couchbase` user. But Openshift, because of security reason, runs a container using a arbitrary user in root group [0]. In the end the server can't run because all the folder belongs to couchbase user and couchbase group.

One way to solve the problem is in [1], which grants permission to run container as the user define in Dockerfile but there are some security concern to that.
The other option is follow the guideline in [0], allow root group to access and run all the file.

In the end i can run couchbase image in Openshift by grant permission to root group and remove `chown couchbase:couchbase` in run script.

So i would like to suggest if we can change Dockerfile and run script to be able to run directly on Openshift.

Thanks.

[0]: https://docs.openshift.com/container-platform/3.5/creating_images/guidelines.html, section `Support Arbitrary User IDs`
[1]: https://docs.openshift.com/container-platform/3.3/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile

**Comment by tleyden** [comment]
Thanks for reporting this!  If you have any steps to reproduce this, it would be helpful.  Eg, scripts you are using to launch or any OpenShift settings to know about.

**Comment by voanhduy1512** [comment]
So here i what i've found so far.

# Step to reproduce:

1) Have a openshift cluster (You can run it on local machine by using [minishift]()
2) Run `oc new-app --docker-image=couchbase`. Basically it will create a service on Openshift using couchbase image and run it.
3) Attach to that pod and run `ps ax` to see all processes and see error:

```
    1 ?        Ss     0:03 runsvdir -P /etc/service log: -server: fatal: unable to open supervise/lock: file does not exist runsv couchbase-server: fatal: unable to open supervise/lock: file does not exist runsv couchbase-server: fatal: unable to open supervise/lock: file does not exist runsv couchbase-server: fatal: unable to open supervise/lock: file does not exist runsv couchbase-server: fatal: unable to open supervise/lock: file does not exist
```

# How i fix it

I made a repo with 2 commits here (based on enterprise 4.6.2) https://github.com/voanhduy1512/couchbase. 

One thing i am not sure it the line `/usr/sbin/runsvdir-start`. I dont think invoke `run` directly is the correct way to do it but i don't know how to fix that runit problem.

Thanks

**Comment by bobbydeveaux** [comment]
AMAZING! Thanks so much @voanhduy1512  - I have finally managed to get @arun-gupta example working! thanks so much!

**Comment by MarcinLachowicz** [comment]
Hello,
@voanhduy1512, it looks like your repo has been removed. Could you please share the solution once again?

**Comment by dustinblack** [comment]
Official image still doesn't work in OpenShift.

In community/couchbase-server/2.2.0/scripts/entrypoint.sh there is a $(whoami) command that fails, ultimately causing the script to abort. In OpenShift, the container is running with a non-privileged UID that doesn't have a name associated, so the whoami command doesn't return anything to stdout, leaving the if statement unable to resolve.

**Comment by ceejatec** [comment]
We have had an official OpenShift image hosted by Red Hat for some time: https://access.redhat.com/containers/?tab=overview#/registry.connect.redhat.com/couchbase/server

It is based on the Official Docker image but has some tweaks necessary for running in OpenShift environments. I'd suggest making use of this.

@dustinblack Thanks for the comment about $(whoami) - you're right, defensively that should be "$(whoami)". I'll make that change for the next release.

**Comment by timm088** [comment]
@ceejatec this fix, https://github.com/couchbase/docker/commit/ce6c779644752958f55cf2635ca36251fdfd4c63 has caused double "" on whoami

Going to take a guess, that as a result of the credentials breach on dockerhub, all images were rebuilt. These images now have a broken shell script within them thats causing failures.

Raised https://github.com/couchbase/docker/issues/123
