### ISSUE TITLE
Docker Hub instructions cause confusion RE: image name

### ISSUE THREAD

**Issue by agonyou** [couchbase/docker#70]
Docs are shown here: https://hub.docker.com/r/couchbase/sync-gateway/ 

From these docs this section caused customer confusion:

docker run -p 4984:4984 -d couchbase-sync-gateway **<<reported to NOT work**
NOTE: until the official docker image is approved, use the staging repository via:

$ docker run -p 4984:4984 -d couchbase/sync-gateway **<< This works**
At this point you should be able to run a curl request against the running Sync Gateway on the port 4984 public port:

**Comment by tleyden** [comment]
@agonyou I fixed it on the master branch, and the next time the docker images are rebuilt and pushed to dockerhub, that change will go up
