### ISSUE TITLE
Use of "ubuntu:12.04"

### ISSUE THREAD

**Issue by tianon** [couchbase/docker#77]
Ubuntu 12.04 reached end of life on April 28, 2017 (http://releases.ubuntu.com/12.04/), and as such the `ubuntu:12.04` image is no longer supported.

It's currently in use by the `couchbase:enterprise-3.1.6` and `couchbase:community-3.1.3` official image tags.  These should either also be deprecated (if Couchbase 3.1 is also no longer supported) or updated to use a newer base.

Thanks!

**Comment by tleyden** [comment]
Thanks @tianon

**Comment by tianon** [comment]
This was fixed by https://github.com/docker-library/official-images/pull/3609. :+1:
