### ISSUE TITLE
Unable to start couchbase when running container with a non user 

### ISSUE THREAD

**Issue by Zizou84** [couchbase/docker#78]
HI,
I'm getting the following status when tryi,g to run couchbase container with a non root  user:

`runsvdir -P /etc/service log: -server: fatal: unable to open supervise/lock: file does not exist runsv couchbase-server: fatal: unable to open supervise/lock: fi`

I know the entrypoint must be called using a root user, but we have a constraint not running container as a root user.
Is there any way/workaround for this?
Thanks

**Comment by tleyden** [comment]
@Zizou84 can you give more details on steps to repro?  Did you modify the Dockerfile and rebuild?  Or are you just running the docker command itself as non-root?  When you say non-root, do you mean on the host or inside the container?

**Comment by Zizou84** [comment]
For example, i got the exception when running the cntainer using the following command(adding --user parameter):
docker run --user couchbase -d --name db -p 8091-8094:8091-8094 -p 11210:11210 couchbase

**Comment by ceejatec** [comment]
I'm afraid that simply won't work with this image as it stands. The startup scripts depend on doing certain tasks as root, specifically ensuring that some files have the correct ownership.

I've just briefly hacked together a modification to the Dockerfile and scripts which, in very limited testing, does allow this to work. I pushed it as "ceejatec/couchbase-server-nonroot:4.6.3", and I also pushed the Dockerfile changes to my fork here: https://github.com/ceejatec/docker

The important limitation with this image is that if you bind-mount /opt/couchbase/var from your host, you must make sure that the host directory you specify already exists AND is owned and writable by user ID 1000 on the host. If you don't use bind-mounting, though, then there really is no downside.

Let me know if this works for you, and if so I'll see if I can merge it into our official image. @tleyden If you could take a look at my fork and see if the change makes sense to you too, I'd appreciate it.

**Comment by Zizou84** [comment]
Great thanks ceejatec,
I will test this image and get back to you .

**Comment by tleyden** [comment]
> The important limitation with this image is that if you bind-mount /opt/couchbase/var from your host, you must make sure that the host directory you specify already exists AND is owned and writable by user ID 1000 on the host. If you don't use bind-mounting, though, then there really is no downside

Would it be possible for the entrypoint script to check that and provide a sensible error message?

**Comment by tleyden** [comment]
@ceejatec yeah those changes look good to me

**Comment by Zizou84** [comment]
I have tested these modifications and looks working as expected.
Great thanks ceejatec .
Just is there any plan to merge this version into the official one (if yes,when can this happens)?

**Comment by Zizou84** [comment]
Hi @ceejatec  @tleyden 
Any plan please about merging this modification?
Thanks

**Comment by tleyden** [comment]
@ceejatec can you push up a pr for your fork?

**Comment by Zizou84** [comment]
Hi @ceejatec @tleyden,
Sorry to insist but any information about this modification?

**Comment by tleyden** [comment]
@ceejatec this is on your plate, can you send a PR?

@Zizou84 you could also submit a PR based on @ceejatec's changes

**Comment by ceejatec** [comment]
Guess I missed this question first time through, @tleyden :

> Would it be possible for the entrypoint script to check that and provide a sensible error message?

Kind of. I've pushed an update to my proposal that does that. It's not a comprehensive check - to really be safe it would need to recursively check every file and directory which could be quite slow. But it at least catches the basic error of not creating the directory with the appropriate ownership first, or creating it non-writable somehow.

**Comment by ceejatec** [comment]
I'm not sure why GitHub didn't add the PR here on the ticket, but here it is: https://github.com/couchbase/docker/pull/87

I feel *pretty* safe merging this, because the only real code additions are explicitly only done when "docker run --user couchbase" is specified which wasn't a supported use case before. I'd still like some sign-off from our testing department if possible, though.

**Comment by ceejatec** [comment]
I'm rebuilding the image to allow for use by a "sandbox" container for demo purposes, so it seemed like a good opportunity to close out some outstanding PRs. This will be in at least the 5.1.0 image, and we'll probably rebuild 5.0.1 with it as well.

**Comment by sudonewdev** [comment]
@ceejatec can you share steps you to allow this work for community-6.6.0 edition?

> I'm afraid that simply won't work with this image as it stands. The startup scripts depend on doing certain tasks as root, specifically ensuring that some files have the correct ownership.
> 
> I've just briefly hacked together a modification to the Dockerfile and scripts which, in very limited testing, does allow this to work. I pushed it as "ceejatec/couchbase-server-nonroot:4.6.3", and I also pushed the Dockerfile changes to my fork here: https://github.com/ceejatec/docker
> 
> The important limitation with this image is that if you bind-mount /opt/couchbase/var from your host, you must make sure that the host directory you specify already exists AND is owned and writable by user ID 1000 on the host. If you don't use bind-mounting, though, then there really is no downside.
> 
> Let me know if this works for you, and if so I'll see if I can merge it into our official image. @tleyden If you could take a look at my fork and see if the change makes sense to you too, I'd appreciate it.
