### ISSUE TITLE
Agenda from Couchbase for being "Cloud Native"

### ISSUE THREAD

**Issue by cha87de** [couchbase/docker#83]
The more I work with Couchbase CE, the more I wonder if this is actually meant to be used with containers in a cloud setup. Two major problems occur:
- the entrypoint does not initialize clusters automatically but requires _manual_ interaction, the official guide even states to use the _web dashboard_ to fulfil this task (#59 #73 #27)
- Couchbase stores the IP addresses of hosts, which limits the benefits clouds and containers provide, it won't be possible to schedule couchbase containers with orchestrators like docker-compose, rancher or kubernetes since the IPs may change (#7 #82)

In order to plan our projects with or without Couchbase: what's on the agenda here from couchbase side? Are there any features missing in the CE version which are part of EE version only? My PR is still pending since months, Ticket #7 is open more than 2 years, is Couchbase even interested in moving towards being cloud native?

Thank you for your support.

**Comment by tleyden** [comment]
Hi @cha87de, thanks for the issue reports, I have raised this internally and will report back to this issue when I find out more.  

I can tell you that there is some exciting work going on with running Couchbase on Kubernetes, which should drive forward some major improvements in this area.

Stay tuned!

**Comment by tleyden** [comment]
Hi @cha87de, thanks for the issue reports, I have raised this internally and will report back to this issue when I find out more.  

I can tell you that there is some exciting work going on with running Couchbase on Kubernetes, which should drive forward some major improvements in this area.

Stay tuned!

**Comment by tleyden** [comment]
Hi @cha87de, thanks for the issue reports, I have raised this internally and will report back to this issue when I find out more.  

I can tell you that there is some exciting work going on with running Couchbase on Kubernetes, which should drive forward some major improvements in this area.

Stay tuned!

**Comment by tleyden** [comment]
Hi @cha87de, thanks for the issue reports, I have raised this internally and will report back to this issue when I find out more.  

I can tell you that there is some exciting work going on with running Couchbase on Kubernetes, which should drive forward some major improvements in this area.

Stay tuned!

**Comment by tleyden** [comment]
Hi @cha87de, thanks for the issue reports, I have raised this internally and will report back to this issue when I find out more.  

I can tell you that there is some exciting work going on with running Couchbase on Kubernetes, which should drive forward some major improvements in this area.

Stay tuned!

**Comment by tleyden** [comment]
Yikes, sorry for all the duplicate comments (deleted).  WiFi was having some issues..

**Comment by tleyden** [comment]
@cha87de here is a short demo of the Couchbase on Kubernetes work that is in progress: https://youtu.be/QyWxWPOoUpM?t=1862

**Comment by tleyden** [comment]
I'm going to close this ticket since it's a bit too broad for a specific action item, but please feel free to continue the discussion here or on the [forums](http://forums.couchbase.com)
