### ISSUE TITLE
Release community-5.0.2 Docker image

### ISSUE THREAD

**Issue by asarkar** [couchbase/docker#85]
The CLI is completely broken in community-5.0.0 due to bug [MB-26556](https://issues.couchbase.com/browse/MB-26556). Can you release community-5.0.2 Docker image with this fix?

**Comment by stevleibelt** [comment]
This ticket should be closed with the release of community-5.0.1 or?

**Comment by tleyden** [comment]
Yes I see a `community-5.0.1` tag, and https://issues.couchbase.com/browse/MB-26556 looks like it was fixed in 5.0.1.  Thanks @stevleibelt!
