### ISSUE TITLE
Run couchbase-server/4.0.0-beta with N1QL

### ISSUE THREAD

**Issue by martinmicunda** [couchbase/docker#9]
Hi,

I tried run your docker `couchbase-server/4.0.0-beta` image with N1QL however I am not able to query through `curl`. I can't see in your [Dockerfile](https://github.com/couchbase/docker/blob/master/enterprise%2Fcouchbase-server%2F4.0.0-beta%2FDockerfile) that you are exposing port `8093`, is this port still required for Couchbase 4 to use N1QL? 

```bash
curl -v http://localhost:8093/query/service -d "statement=SELECT * FROM default WHERE type = 'partner'" 
```

```bash
 Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8093 (#0)
> POST /query/service HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8093
> Accept: */*
> Content-Length: 54
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 54 out of 54 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Comment by tleyden** [comment]
Hi @martinmicunda -- how did you launch the docker container?

**Comment by martinmicunda** [comment]
@tleyden through `docker-compose`

```yml
db:
  image: couchbase/server:enterprise-4.0.0-beta #server:community-3.0.1
  ports:
    - "8091:8091"
    - "8093:8093" # N1QL
    - "11210:11210" # this should not be required once I will get link containers work together
```

**Comment by tleyden** [comment]
What happens if you try port 8091?

`curl -v http://localhost:8091`

**Comment by martinmicunda** [comment]
It doesn't work when try use query. Is `8093` port deprecated now or how do you running N1QL through `couchbase/server:enterprise-4.0.0-beta`?

```
vagrant@employee-scheduling:~$ curl -v http://localhost:8091
* Rebuilt URL to: http://localhost:8091/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8091 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8091
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
* Server Couchbase Server is not blacklisted
< Server: Couchbase Server
< Pragma: no-cache
< Location: http://localhost:8091/index.html
< Date: Sat, 18 Jul 2015 16:21:02 GMT
< Content-Type: text/html
< Content-Length: 233
< Cache-Control: no-cache
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="http://localhost:8091/index.html>here</a>.</p></body></html>
* Connection #0 to host localhost left intact
```

**Comment by tleyden** [comment]
Looks like 8093 is the right port.

@geraldss any idea on this?

**Comment by martinmicunda** [comment]
so shouldn't be port `8093` add to `Dockerfile`?

**Comment by tleyden** [comment]
I don't think that's actually required for what you are trying to do.

```
EXPOSE
EXPOSE <port> [<port>...]
The EXPOSE instructions informs Docker that the container will listen on the specified network ports at runtime. Docker uses this information to interconnect containers using links (see the Docker User Guide) and to determine which ports to expose to the host when using the -P flag.

Note: EXPOSE doesn’t define which ports can be exposed to the host or make ports accessible from the host by default. To expose ports to the host, at runtime, use the -p flag or the -P flag.
```

**Comment by geraldss** [comment]
Yes, 8093 is the default, but it is configurable.

**Comment by martinmicunda** [comment]
@geraldss have you tried to use N1QL with this `couchbase/server:enterprise-4.0.0-beta` image and run queries through curl e.g.

```bash
curl -v http://localhost:8093/query/service -d "statement=SELECT * FROM default WHERE type = 'partner'" 
```

**Comment by geraldss** [comment]
@martinmicunda, I ran your curl command locally, but not in docker:

Geralds-MacBook-Pro-2:~ gerald$ curl -v http://localhost:8093/query/service -d "statement=SELECT * FROM default WHERE type = 'partner'"
* Adding handle: conn: 0x7faf6300a600
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7faf6300a600) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 8093 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8093 (#0)
> POST /query/service HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:8093
> Accept: */*
> Content-Length: 54
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 54 out of 54 bytes
< HTTP/1.1 200 OK
< Content-Length: 304
< Content-Type: application/json; version=0.8.1
< Date: Sat, 18 Jul 2015 16:36:12 GMT
< 
{
    "requestID": "3df5b4af-34ab-4df6-97ff-ae7a1f0a588c",
    "signature": {
        "*": "*"
    },
    "results": [
    ],
    "status": "success",
    "metrics": {
        "elapsedTime": "57.459141ms",
        "executionTime": "57.139856ms",
        "resultCount": 0,
        "resultSize": 0
    }
}
* Connection #0 to host localhost left intact

**Comment by martinmicunda** [comment]
@geraldss hmm I try run that against this docker image however port `8093` doesn't work...

**Comment by martinmicunda** [comment]
Is there any updated on this? Has anybody try run N1QL with this docker container? Thanks

**Comment by ceejatec** [comment]
Indeed, I can confirm this isn't working in the 4.0.0-beta Docker image. I have re-created the image locally based on a newer build of Couchbase Server 4.0.0, and it works as expected. I am inquiring internally to see if I can push this version out to allow more external testing.

Sorry for the inconvenience!

**Comment by martinmicunda** [comment]
@ceejatec Thanks!

**Comment by tleyden** [comment]
@ceejatec I'm not seeing the 4.0.0-3508 build you mentioned here:

https://registry.hub.docker.com/u/couchbase/server/tags/manage/

**Comment by ceejatec** [comment]
I never got permission to push it public. :( I never got explicit non-permission either; I will try again.

**Comment by tleyden** [comment]
I think 4.0 rc2 is coming out very soon (tomorrow?).  I think we should push that, and delete the other tags with older 4.0's avoid confusion.

**Comment by martinmicunda** [comment]
@tleyden @ceejatec have anybody pushed the fix for this yet? Thanks

**Comment by tleyden** [comment]
I haven't had a chance yet.

@ceejatec do you know the url for the ubuntu .deb package?

**Comment by ceejatec** [comment]
Well, it's only constructed out of publicly-available parts, so I went ahead and pushed a new build for 4.0.0-3508. Please note there's nothing special about this build, it's just a later build that I've confirmed doesn't have the problem reported here; port 8093 is responding. It is otherwise not any kind of "official" build. But hopefully it will allow further N1QL testing for interested parties!

Docker hub image name: couchbase/server:enterprise-4.0.0-3508

**Comment by ceejatec** [comment]
(Aside: sorry for the delay in getting this done, and thanks for your interest!)

**Comment by ceejatec** [comment]
FYI: there is now a release-candidate version of the image which also works - couchbase/server:enterprise-4.0.0-rc0
